package app.guitar.theory

/** Real-song ear-training workout: ONE 4-month curriculum, merged and expanded by
 *  Claude from Nadav's ChatGPT material (the two curriculum PDFs + the full
 *  203-page conversation). See
 *  docs/superpowers/specs/2026-08-03-ear-workout-theory-tab-design.md.
 *
 *  Structure: 4 months × 4 weeks × 4 sessions = 64 song-sessions. Every session
 *  is a REAL song run through the same 45-minute frame ([SESSION_FRAME]);
 *  synthetic progressions are train-ride work ([TRAIN_DRILLS]), never a session.
 *  Each MONTH introduces exactly one new listening objective; harmony, melody,
 *  bass, harmonization and prediction are trained EVERY week (spiral), only the
 *  complexity rises.
 *
 *  Spoilers live in [WorkoutSession.spoiler] and must stay hidden until an
 *  attempt is made. Mirrored in chorect-web earWorkout.ts. */

/** A named recording. [version] pins the performance the exercise was built on. */
data class WorkoutSong(val title: String, val artist: String, val version: String? = null)

/** One 45-minute session on one song. [song] is null for student-choice/exam
 *  sessions ([songNote] then says what to pick). */
data class WorkoutSession(
    val number: Int,        // 1..64
    val title: String,
    val song: WorkoutSong?,
    val songNote: String? = null,
    /** Function/structure to notice. */
    val focus: String,
    /** The quality discrimination this session trains (the real bottleneck). */
    val quality: String,
    /** Stage-appropriate melody-playback goal. */
    val melody: String,
    /** Constrained harmonization task. */
    val harmonization: String,
    val passGoal: String,
    /** Appendix answer — keep hidden until you've attempted. */
    val spoiler: String = "",
    /** Set when the answer is a clean 4-bar diatonic loop the app can play. */
    val loop: Progression? = null,
)

/** One week: a single listening objective + 4 sessions + the week's prediction
 *  drill and grading boundaries. */
data class WorkoutWeek(
    val week: Int,          // 1..16
    val month: Int,         // 1..4
    val title: String,
    /** Predict-the-next-FUNCTION drill for this week (unfamiliar song). */
    val prediction: String,
    /** Arrangement details that must NOT count against you this week. */
    val notGraded: List<String>,
    val sessions: List<WorkoutSession>,
) {
    init { require(sessions.size == 4) { "week $week must have 4 sessions, got ${sessions.size}" } }
}

/** A month-end examination. */
data class WorkoutExam(val timeLimit: String, val requirements: List<String>, val passStandard: String)

/** One month: its single new objective, harmonization level, train-ride focus,
 *  monthly transcription project and exam. */
data class WorkoutMonth(
    val number: Int,
    val title: String,
    val objective: String,
    val vocabulary: String,
    val harmonizationRule: String,
    val melodyStage: String,
    /** Which [TRAIN_DRILLS] categories to run on train rides this month. */
    val trainFocus: String,
    /** The once-a-month complete-transcription graduation project. */
    val project: String,
    val exam: WorkoutExam,
)

object EarWorkout {

    // ==================================================================================
    // Where you are, what you're aiming at, how to practise
    // ==================================================================================

    /** The six master goals everything else serves. */
    val MASTER_GOALS: List<Pair<String, String>> = listOf(
        "1 · Functional harmony" to "Hear a song once and understand its harmonic structure — key, Roman numerals, cadences, secondary dominants, borrowed chords, ii–V–I.",
        "2 · Melodic audiation" to "Hear a melody and reproduce it immediately, without searching. You can sing it before you play it.",
        "3 · Harmonization" to "Hear a simple melody and instinctively know several good harmonic choices. The most “musician” goal of them all.",
        "4 · Complete song transcription" to "Learn whole songs by ear — progression, melody, bass, important fills — without tabs or charts.",
        "5 · Real-time playing" to "Hear music and play along naturally, almost like speaking another language.",
        "North star" to "Become the guitarist who can hear an unfamiliar song once, play along, explain why the harmony works, and build a convincing accompaniment if the original chords disappeared.",
    )

    /** Honest starting profile (from the assessment conversation). */
    val PROFILE: List<Pair<String, String>> = listOf(
        "Theory" to "Advanced",
        "Functional hearing — diatonic" to "Strong",
        "Functional hearing — chromatic" to "Developing",
        "Melody playback" to "Developing (partly note-by-note searching)",
        "Harmonization" to "Beginning",
        "Song transcription" to "Developing",
        "Rhythm" to "Strong — NOT a bottleneck, so no rhythmic dictation in this plan",
    )

    /** The three real bottlenecks this curriculum attacks. */
    val BOTTLENECKS: List<String> = listOf(
        "SPEED — you can analyse a secondary dominant, a borrowed chord or an inversion, but it takes conscious reasoning. The goal is for the ear to say “that's V/V” before the analytical brain starts.",
        "WHOLE STRUCTURES — you hear “that's IV”. The next level is “we're approaching a cadence”, “this phrase is prolonging tonic”, “they're delaying the dominant”.",
        "HEAR → FINGERS — you hear something, then search on the guitar. The target is almost no conscious step between hearing and playing.",
    )

    /** Global practice/evaluation rules — they apply to every session. */
    val GLOBAL_RULES: List<String> = listOf(
        "Always start guitarless. Not to name the key — to build an internal guess before the instrument confirms it.",
        "Work directly in FUNCTION. Once the tonal centre is located, the guitar is an interval instrument: function is your native representation, and the chord names are just its spelling in that key.",
        "One hypothesis at a time on guitar: test a predicted root, quality or bass position instead of fishing through shapes.",
        "Function before spelling: a correct functional category with an uncertain inversion is partial success, not a wrong answer.",
        "Arrangement details are bounded — each week lists what is NOT graded, so an ornament or voicing can't read as your ear failing.",
        "Synthetic progressions are TRAIN-RIDE work, never a 45-minute session. Sessions are real songs only.",
        "Don't spend 45 minutes perfecting one chord. Move on. The goal is many musical examples in your ear, not one flawless transcription.",
        "Don't open a session's spoiler until you've made a serious attempt. It's a checking guide, not a chart to memorize.",
    )

    /** The 45-minute session frame — identical every session. */
    val SESSION_FRAME: List<Pair<String, String>> = listOf(
        "0–5" to "Guitarless listen: how many chords repeat, where the changes are, can you hum the bass and the melody, does anything sound outside/dominant-like, where does it resolve.",
        "5–18" to "Function + quality identification on guitar: bass/function → triad quality → seventh quality → special function (V/x, borrowed, ii–V, deceptive).",
        "18–25" to "SPEED LOOP: loop 4–8 bars and call the function + quality IN TIME. Not perfectly — faster. This is the bottleneck drill.",
        "25–33" to "Melody playback (see the month's melody stage).",
        "33–42" to "Constrained harmonization (see the month's rule).",
        "42–45" to "Play-through as music: bass → chords → melody → your reharmonization. No written log; the output is that you can play and explain it.",
    )

    const val MASTERY_RULE =
        "Don't advance because four weeks passed — advance when you PASS the month exam. If a month takes six weeks, fine. If you pass early, move on early. " +
            "The calendar is a guideline; the exams define progress."

    const val HARMONIZATION_LADDER =
        "Level 1: the melody note must be the root, 3rd or 5th of the chord you choose.  Level 2: it may also be the 7th when the function is clear.  " +
            "Level 3: 9ths/11ths/13ths only when the function is ALREADY clear. Without this ladder, almost any chord can be “justified” by extending it to contain the melody note — and the exercise loses its teeth."

    /** How the timeline scales with weekly practice time (baseline 3 h/week). */
    val TIME_SCALING: List<Pair<String, String>> = listOf(
        "1.5 h/week" to "≈8 months for these 4 months — possible, but fewer songs stick deeply",
        "2 h/week" to "≈6 months — good maintenance pace",
        "3 h/week" to "4 months — the baseline this plan assumes (4 sessions × 45 min)",
        "4 h/week" to "≈3 months, if you still review",
        "5–6 h/week" to "≈2–2.5 months — serious-student pace",
        "Note" to "It does not scale linearly: three short sessions across the week beat one long block. Repeated exposure and sleep consolidation do the work.",
    )

    /** Realistic expected progress after these 4 months at ~3 h/week. */
    val EXPECTED_PROGRESS: List<Pair<String, String>> = listOf(
        "Diatonic functional hearing" to "85–95%",
        "Secondary-dominant recognition" to "60–80%",
        "Borrowed-chord recognition" to "70–85%",
        "Brazilian / diminished harmony" to "50–70%",
        "Instant simple-melody playback" to "60–80%",
        "Harmonizing simple melodies" to "70–85%",
        "Full song transcription" to "60–80%",
        "Real-time accompaniment" to "50–75%",
    )

    /** How this compares with a Berklee-style degree. */
    val BERKLEE: List<Pair<String, String>> = listOf(
        "Harmony recognition" to "This plan is stronger — it's the whole point",
        "Song transcription from recordings" to "This plan is the main method; Berklee treats it as one activity among many",
        "Harmonization / reharmonization" to "Central here; at Berklee it arrives through harmony & arranging classes",
        "Playing by ear / live accompaniment" to "Central here",
        "Melodic dictation" to "Berklee stronger (graded, notation-based)",
        "Rhythmic dictation" to "Berklee much stronger — deliberately skipped here, it isn't your bottleneck",
        "Sight singing (movable Do)" to "Berklee much stronger — replaced here by thinking in scale degrees, which you already do",
        "Notation / sight reading" to "Berklee stronger",
    )

    /** What to chase after these four months. */
    val FUTURE_GOALS: List<String> = listOf(
        "Transcribe full guitar parts, not just chords and melody.",
        "Transcribe 30–60 second solos.",
        "Build chord-melody arrangements by ear.",
        "Harmonize one melody in four styles: folk, country, bossa, jazz.",
        "Improvise from the melody rather than from scales.",
        "Recognize chord extensions by ear: 9, ♭9, #11, 13.",
        "Recognize modulations instantly.",
        "Arrange one full song per month for guitar + voice.",
        "Build a 50-song internal repertoire you can play, analyse and reharmonize.",
        "Play with singers without charts. Graduation test: someone sings you a melody, you immediately play it, harmonize it, accompany them, then produce a nicer second version.",
    )

    /** Train-ride synthetic pool, by category. Quick reaction, not deep analysis. */
    val TRAIN_DRILLS: List<Pair<String, String>> = listOf(
        "Diatonic 7th loops" to "Imaj7–vi7–IVmaj7–V7 | Imaj7–vi7–ii7–V7 | Imaj7–IVmaj7–ii7–V7 | vi7–ii7–V7–Imaj7",
        "Pre-dominant → dominant" to "I–IV–V–I | I–ii–V–I | I–vi–ii–V | vi–ii–V–I",
        "Tonic substitutes & deception" to "I–V–vi–IV | I–iii–vi–IV | I–V–vi | I–iii–IV–V",
        "V/V" to "I–V/V–V–I | I–IV–I–V/V–V–I | I–vi–ii–V/V–V–I",
        "V/vi and V/ii" to "I–III7–vi | I–V/vi–vi–IV–V | I–VI7–ii–V–I | I–V/ii–ii–V–I",
        "ii–V–I / jazz cadences" to "ii–V–I | vi–ii–V–I | I–VI7–ii–V–I | I–III7–vi–II7–V–I",
        "Borrowed & modal" to "I–IV–iv–I | I–♭VII–IV–I | I–♭VI–♭VII–I | I–♭III–IV–I | I–iii–♭III–ii–V",
        "Minor-key motion" to "i–iv–V7–i | i–♭VII–♭VI–V | ii°–V7–i | i–iv–#iv°–V",
        "Diminished approach" to "I–#I°–ii–V | ii–#ii°–iii–VI7 | i–#iv°–V | iv–#iv°–i  (#I°→ii, #ii°→iii, #iv°→V)",
        "Brazilian / bossa loops" to "Imaj7–#I°–ii7–V7 | iii7–VI7–ii7–V7 | Imaj7–VI7–ii7–V7 | I–I7–IV–iv–I",
        "Quick questions" to "Diatonic or outside? maj7, m7 or dom7? Where does the dominant want to resolve? Is this ii–V–I? Borrowed colour, modal colour, or a real modulation?",
        "Order of mastery" to "1 I–V–vi–IV · 2 I–ii–V–I · 3 I–iii–vi · 4 I–V/V–V–I · 5 I–III7–vi · 6 I–VI7–ii–V–I · 7 I–IV–iv–I · 8 I–♭VII–IV–I · 9 I–#I°–ii–V · 10 Imaj7–VI7–ii7–V7",
    )

    // ==================================================================================
    // The four months
    // ==================================================================================

    val MONTHS: List<WorkoutMonth> = listOf(
        WorkoutMonth(1, "Diatonic function and quality, at speed",
            objective = "Call function AND triad quality in ordinary loops without stopping to reason. Build the reflex before adding colour.",
            vocabulary = "I, ii, IV, V, vi (+ a first taste of V/V and V/IV).",
            harmonizationRule = "Level 1 — the melody note must be the root, 3rd or 5th of the chord you choose. No extensions as justification.",
            melodyStage = "Note-by-note searching is acceptable. Accuracy over fluency.",
            trainFocus = "Diatonic 7th loops · Pre-dominant → dominant · Tonic substitutes & deception · V/V",
            project = "Month project: one complete transcription of a simple song you've never learned — progression, bass, melody, and your own harmonization of one phrase.",
            exam = WorkoutExam("45 minutes, unfamiliar simple pop/country/folk song",
                listOf("Identify the main functional loop", "Name every chord quality: major / minor / dominant",
                    "Play one recognizable melody phrase", "Build a 2–4 bar triadic harmonization (Level 1 rule)",
                    "Identify any V/V, V/vi or V/ii if obvious"),
                "Pass on a usable musician result, not a perfect transcription.")),
        WorkoutMonth(2, "Dominant arrows, sevenths, and ii–V as one object",
            objective = "Hear a dominant as an ARROW and name its target. Kill the specific confusions your All-of-Me attempt exposed: iii vs III7, vi vs VI7, ii vs II7.",
            vocabulary = "maj7, m7, dom7, m7♭5; V/V, V/vi, V/ii, V/IV; ii–V–I; inversions (bass on the 3rd).",
            harmonizationRule = "Level 2 — the melody may also be the 7th when the function is clear. Extensions still off-limits.",
            melodyStage = "Aim for 2–3 note chunks instead of single notes.",
            trainFocus = "V/vi and V/ii · ii–V–I / jazz cadences · Diatonic 7th loops (quality only)",
            project = "Month project: one complete transcription of an unfamiliar old standard — form, functions, melody, and every dominant named by its target.",
            exam = WorkoutExam("45 minutes, unfamiliar standard-like song with at least one outside dominant",
                listOf("Roots and functions of an eight-event excerpt (≥6 of 8)", "Every seventh quality: maj7 / m7 / dom7 (≥8/10)",
                    "Each outside dominant identified BY ITS TARGET", "Distinguish ii from IV and iii from vi where relevant",
                    "A 6–8 note melody phrase, correct contour", "A Level-2 harmonization that sounds musical"),
                "Pass if you can accompany it, explain its functions, and reshape a small section.")),
        WorkoutMonth(3, "Borrowed colour and modal mixture",
            objective = "Hear a chord from outside the key as COLOUR rather than as a mistake — and stop mistaking modal motion for dominant function.",
            vocabulary = "iv, ♭VII, ♭VI, ♭III; iii vs vi; minor i–iv–V; major/minor ambiguity.",
            harmonizationRule = "Level 2, plus borrowed chords: use iv / ♭VII / ♭VI only when the melody note sits in THAT chord's triad (iv = 4, ♭6, 1; ♭VII = ♭7, 2, 4).",
            melodyStage = "Short phrases before playing — stop hunting note by note.",
            trainFocus = "Borrowed & modal · Minor-key motion · Tonic substitutes & deception",
            project = "Month project: one complete transcription of an unfamiliar Beatles / classic-rock song, with every non-diatonic chord classified as borrowed, modal or applied dominant.",
            exam = WorkoutExam("60 minutes, unfamiliar song containing modal mixture",
                listOf("Identify the borrowed chords and describe their colour", "♭VII vs V discrimination (≥8/10)",
                    "Minor-key function: i, iv, natural v vs major V", "Use one borrowed chord in your OWN harmonization, melody intact",
                    "An 8–10 note melody phrase", "Reduce a dense section to a functional skeleton"),
                "Pass if the skeleton is usable with at most one wrong function, and no modal chord was called a dominant.")),
        WorkoutMonth(4, "Brazilian harmony: diminished motion, chromatic dominants, modulation",
            objective = "Hear diminished chords as MOTION into a target, follow chromatic dominants, and notice when the key itself moves — in the repertoire you actually play.",
            vocabulary = "#I°→ii, #ii°→iii, #iv°→V; II7, VI7, III7 chains; tritone substitution; modulation to the relative major/minor; maj7/m7/dom7 as ordinary colour.",
            harmonizationRule = "Level 3 opens — extensions allowed, but only where the function is already unmistakable. Approach a target chord by its dominant or by a diminished passing chord.",
            melodyStage = "A full A-section, correct contour and ≥80% exact pitches.",
            trainFocus = "Diminished approach · Brazilian / bossa loops · V/vi and V/ii",
            project = "Month project: one complete transcription of an unfamiliar samba or bossa — a usable chord chart, the melody, the devices named, plus a simpler “campfire” version that still supports the melody.",
            exam = WorkoutExam("One listen + 90 minutes, unfamiliar song (prefer one with a modulation or a chromatic dominant)",
                listOf("Identify the key and play along after the first section", "Map the form by function (≥75% of events)",
                    "Name each chromatic/diminished device by where it resolves", "Detect any modulation and name the new tonic",
                    "Play the main melody", "Create one alternative harmonization", "Perform a basic guitar+melody version from your own lead sheet"),
                "Pass if you can hear, understand, play and reshape real music — that is the whole plan's goal.")),
    )

    // ==================================================================================
    // Helpers
    // ==================================================================================

    private fun maj(vararg d: Int) = Progression(TrainingMode.Major, d.toList())
    private fun sng(title: String, artist: String, version: String? = null) = WorkoutSong(title, artist, version)

    // ==================================================================================
    // The 16 weeks / 64 sessions
    // ==================================================================================

    val WEEKS: List<WorkoutWeek> = listOf(

        // ---------------------------------- MONTH 1 ----------------------------------
        WorkoutWeek(1, 1, "The core loop — and what quality each event has",
            prediction = "Put on an unfamiliar simple song. After 3–6 chord changes, pause and predict the next FUNCTION (tonic / pre-dominant / dominant / deceptive) — not the chord name. Resume and compare.",
            notGraded = listOf("Famous bass figures", "Exact instrumental voicings", "Optional 7th colour added by one instrument"),
            sessions = listOf(
                WorkoutSession(1, "Four events, four colours",
                    sng("Stand by Me", "Ben E. King", "original 1961 single"),
                    focus = "Four events per cycle: which is home, which is the soft one, which prepares, which pulls? Don't assume the bass riff spells the chord roots.",
                    quality = "major → minor → major → dominant/major. The soft chord is minor but still close to home.",
                    melody = "First vocal phrase. Note-by-note searching is fine; aim for a recognizable contour.",
                    harmonization = "2 bars using only I, vi, IV, V. Melody must be root/3rd/5th.",
                    passGoal = "Call the four events in order with correct qualities, in time, after a few repetitions.",
                    spoiler = "Key A major: I – vi – IV – V (A – F#m – D – E), repeating all song.",
                    loop = maj(1, 6, 4, 5)),
                WorkoutSession(2, "Resolved against avoided",
                    sng("Let It Be", "The Beatles", "original 1970 recording"),
                    focus = "Hear when the dominant lands home and when it side-steps to the soft relative-minor chord instead. Two loops can share three chords and differ only in where they land.",
                    quality = "All majors plus one minor — so this is a FUNCTION exercise, not a quality one.",
                    melody = "Chorus melody, in short chunks where you can.",
                    harmonization = "Harmonize one phrase, then replace one IV with ii — only if the melody note is 4 or 6 (the tones IV and ii share).",
                    passGoal = "Classify every phrase ending as RESOLVED or AVOIDED, guitarless.",
                    spoiler = "Sections include I – V – vi – IV and I – V – IV – I. The lesson is V→vi (avoided) against V→I (resolved).",
                    loop = maj(1, 5, 6, 4)),
                WorkoutSession(3, "Clean quality, no clutter",
                    sng("I Can See Clearly Now", "Johnny Nash", "original"),
                    focus = "Simple functional direction with nothing in the way. Use it to make the major/minor call instant.",
                    quality = "Major vs minor triad, at speed. Nothing harder.",
                    melody = "Chorus or main hook; long notes first.",
                    harmonization = "Harmonize a short phrase with basic triads that contain the melody note.",
                    passGoal = "Accompany the main section and call each quality without hesitating.",
                    spoiler = "Simple major-key function around I, IV and V, with occasional relative-minor colour depending on section/version."),
                WorkoutSession(4, "A stable chord starts pointing somewhere",
                    sng("Something", "The Beatles", "original (Abbey Road) — opening/verse only"),
                    focus = "Listen for a settled chord gaining tension and forward motion. Do NOT analyse the whole song — the opening phrase is the lesson.",
                    quality = "Plain major against the same chord turned dominant. That added note is the whole point.",
                    melody = "The opening vocal phrase only.",
                    harmonization = "A plain triadic version first; then one version where a chord points into the next — melody must be root/3rd/5th of that chord.",
                    passGoal = "You hear a chord gaining directional colour rather than just becoming “weird”.",
                    spoiler = "The opening teaches I → I7-ish colour → IV direction (i.e. V/IV → IV), plus chromatic line colour."),
            )),

        WorkoutWeek(2, 1, "Pre-dominant choices: ii against IV",
            prediction = "Same drill, harder: after a few changes, predict the next TWO functions. Score yourself on whether your first guess was one of the musically likely options, not on exactness.",
            notGraded = listOf("Guitar embellishments", "Strumming patterns", "Added 7ths in simplified charts"),
            sessions = listOf(
                WorkoutSession(5, "Two ways to prepare the dominant",
                    sng("Take Me Home, Country Roads", "John Denver", "original"),
                    focus = "Compare two chords that both prepare the dominant but differ in quality and colour.",
                    quality = "Minor pre-dominant against major pre-dominant.",
                    melody = "Opening vocal phrase; find the long notes before the decorations.",
                    harmonization = "Two versions of one phrase: I–IV–V–I and I–ii–V–I. Keep whichever contains the melody better.",
                    passGoal = "Choose between similar functions using both quality and melody, and say why.",
                    spoiler = "Mostly the I, IV, V, vi family. Listen for pre-dominant alternatives and cadences."),
                WorkoutSession(6, "Same quality, different function",
                    sng("Brown Eyed Girl", "Van Morrison", "original"),
                    focus = "Both home and away chords are major — so quality can't help you. Function is all you have.",
                    quality = "Identical quality, different job: notice how IV opens a phrase and V closes it.",
                    melody = "Main vocal hook. Is it mostly chord tones or passing notes?",
                    harmonization = "One alternate version using vi — allowed only when the melody note is 6, 1 or 3.",
                    passGoal = "Distinguish function even when the chord quality is identical.",
                    spoiler = "Common verse feel: I – IV – I – V.",
                    loop = maj(1, 4, 1, 5)),
                WorkoutSession(7, "The melody narrows the choice",
                    sng("Wonderful Tonight", "Eric Clapton", "original"),
                    focus = "A melody note doesn't determine a chord — it narrows the possibilities. Harmonization is constrained choice, not guessing.",
                    quality = "Major triads only; the work is in the choosing.",
                    melody = "Find the long vocal notes before the ornaments.",
                    harmonization = "For each important melody note, list EVERY triad containing it (degree 1 → I, IV, vi; degree 5 → I, iii, V), then pick the most functional one.",
                    passGoal = "You can justify each chord from the melody note plus the phrase direction.",
                    spoiler = "Simple major-key I, V, IV area — ideal for melody constraining chord choice."),
                WorkoutSession(8, "Same start, different end",
                    sng("Knockin' on Heaven's Door", "Bob Dylan", "original 1973 soundtrack recording"),
                    focus = "Two cycles share an opening and diverge at the end. Never let a familiar opening make you assume the ending.",
                    quality = "The minor pre-dominant against the major one — ii is darker and more directed, IV broader.",
                    melody = "5–6 notes of a verse phrase. Which chord better contains the melody note: ii or IV?",
                    harmonization = "Build both endings; keep the one the melody actually supports.",
                    passGoal = "Distinguish the two cycle endings guitarless, and give every harmony's broad quality.",
                    spoiler = "Key G major, alternating: I – V – ii and I – V – IV (G – D – Am and G – D – C). As a 4-bar loop, cycle 1 sits as I – V – ii – ii.",
                    loop = maj(1, 5, 2, 2)),
            )),

        WorkoutWeek(3, 1, "Familiar loops across styles — speed over perfection",
            prediction = "Predict where the PHRASE will resolve, not just the next chord: “this is building tension, I expect it to end on V”, “this sounds like it's finishing, I expect an authentic cadence”.",
            notGraded = listOf("Groove and feel", "Organ/keyboard fills", "Melodic decorations"),
            sessions = listOf(
                WorkoutSession(9, "The same loop in a different suit",
                    sng("I'm Yours", "Jason Mraz", "original"),
                    focus = "Recognize a loop you already know inside an unfamiliar arrangement. Train speed, not perfection.",
                    quality = "major → dominant → minor → major, called in time.",
                    melody = "Chorus melody; try to hear 2-note chunks rather than single notes.",
                    harmonization = "Replace one chord only if the melody note fits the new triad.",
                    passGoal = "You call the functions faster than you did in week 1.",
                    spoiler = "Common loop: I – V – vi – IV. Note the V→vi avoided resolution.",
                    loop = maj(1, 5, 6, 4)),
                WorkoutSession(10, "Two endings for one melody",
                    sng("Have You Ever Seen the Rain", "Creedence Clearwater Revival", "original"),
                    focus = "Compare true resolution with a relative-minor landing, back to back.",
                    quality = "The emotional difference between “home” and “relative minor”.",
                    melody = "Chorus melody; mark where each phrase feels unresolved.",
                    harmonization = "Two endings for the same melody: V→I and V→vi. The final melody note must belong to the final chord's triad.",
                    passGoal = "You hear — and can create — the difference between an authentic and a deceptive cadence.",
                    spoiler = "The I, V, vi, IV family; compare V→I with V→vi."),
                WorkoutSession(11, "Circular, never quite finished",
                    sng("No Woman, No Cry", "Bob Marley & The Wailers", "studio or the 1975 Live! version"),
                    focus = "Phrase circularity: the loop keeps returning home without sounding finished each time.",
                    quality = "Same function family as sessions 2 and 9, different feel — recognize the grammar across style.",
                    melody = "Main vocal phrase, long notes first.",
                    harmonization = "Make the pre-dominant more directed: replace IV with ii where the melody is 4 or 6.",
                    passGoal = "The loop feels familiar rather than newly confusing.",
                    spoiler = "Loop family: I – V – vi – IV / I – IV – I – V depending on section and version.",
                    loop = maj(1, 5, 6, 4)),
                WorkoutSession(12, "A change is not an accent",
                    sng("La Bamba", "Ritchie Valens", "original 1958 recording"),
                    focus = "The groove accents far more often than the harmony moves. Separate a real chord CHANGE from a strong rhythmic hit.",
                    quality = "Three primary majors — count the chords before naming any of them.",
                    melody = "One sung phrase of 4–6 notes; label the degrees.",
                    harmonization = "Harmonize the phrase with I, IV and V only.",
                    passGoal = "The right number of chords per cycle, and change points that survive a second listen.",
                    spoiler = "I – IV – V (in concert-pitch representation C – F – G), repeating; as a 4-bar loop I – IV – V – I. Voicing can briefly suggest dominant-7 colour.",
                    loop = maj(1, 4, 5, 1)),
            )),

        WorkoutWeek(4, 1, "Integration, first chromatic push, and the Month 1 exam",
            prediction = "Blind: play an unfamiliar song and call functions live, out loud, for a whole verse. Accept errors; keep the pulse.",
            notGraded = listOf("Anything outside the assigned fragment", "Exact bass position under the dominant"),
            sessions = listOf(
                WorkoutSession(13, "An extra push into the dominant",
                    sng("Leaving on a Jet Plane", "John Denver", "or the Peter, Paul and Mary version"),
                    focus = "Hear an added push into V — the dominant of the dominant.",
                    quality = "A dominant-quality chord built on scale degree 2. It contains a chromatic #4, which is exactly why it sounds like a push.",
                    melody = "Verse melody; find where the melody supports the cadence.",
                    harmonization = "Turn I–IV–V–I into I–IV–V/V–V–I — but only if the melody note is 2, #4 or 6 (the V/V triad). If the melody is a natural 4, it will clash.",
                    passGoal = "You hear forward pull rather than “an extra chord”, and you understand why secondary dominants bring chromatic notes.",
                    spoiler = "Mostly the I – IV – V – I family; optional colour V/V → V before a cadence in some versions."),
                WorkoutSession(14, "The tonic itself turns into a dominant",
                    sng("You Are My Sunshine", "traditional", "ONLY a version containing I7 → IV"),
                    songNote = "Caveat: most simple versions are plain I–IV–V and teach nothing here. The secondary dominant in this song is not a new root — it's the tonic becoming a dominant 7th so it points at IV. If your version lacks that, use the song as plain function practice.",
                    focus = "Hear a stable home chord altered so that it points at IV.",
                    quality = "Major tonic against dominant-7 tonic — the single easiest secondary dominant to hear.",
                    melody = "Chorus melody.",
                    harmonization = "A plain version, then a forward-pointing version, only where the melody fits the altered chord.",
                    passGoal = "You hear the difference between plain home and home turned into a dominant colour.",
                    spoiler = "Versions with the lab move read I → I7 → IV, i.e. V7/IV → IV."),
                WorkoutSession(15, "Girl — controlled micro-lab (two loops only)",
                    sng("Girl", "The Beatles", "original 1965 — verse opening and chorus ONLY"),
                    songNote = "This is the song that exhausted you. Do NOT transcribe it. Two loops, diagnostic only — the vocabulary it really needs arrives in month 3, where the song returns.",
                    focus = "Loop A: the minor-tonic verse opening and its dominant pull. Loop B: the chorus, which genuinely shifts to a new home.",
                    quality = "Loop A: minor tonic vs dominant 7. Loop B: major → minor → minor → dominant.",
                    melody = "One phrase you already found. Fluency, not new material.",
                    harmonization = "None. This session is diagnosis.",
                    passGoal = "You can say that the chorus moved home, and that its second chord is NOT the relative minor of a doo-wop loop.",
                    spoiler = "Verse opening: i – V7 – i. Chorus (relative major): I – iii – ii – V7 — its shape resembles doo-wop I – vi – IV – V, but iii is not vi and ii is not IV.",
                    loop = maj(1, 3, 2, 5)),
                WorkoutSession(16, "MONTH 1 EXAMINATION",
                    song = null, songNote = "An unfamiliar simple song: pop, country, folk or classic rock.",
                    focus = "Everything from month 1, cold, with nothing prepared. See the Month 1 exam card for requirements.",
                    quality = "Major / minor / dominant, named for every event.",
                    melody = "One recognizable melody phrase.",
                    harmonization = "A 2–4 bar triadic harmonization under the Level-1 rule.",
                    passGoal = "Pass on a usable musician result. Then — and only then — move to month 2 (mastery rule).")
            )),

        // ---------------------------------- MONTH 2 ----------------------------------
        WorkoutWeek(5, 2, "The dominant arrow — hear it by its target",
            prediction = "When you hear an outside chord, predict its TARGET before it arrives, then check. “Where does this want to go?” beats “what is this chord called?”.",
            notGraded = listOf("Extensions above the seventh", "Rhythm-section decoration", "Performance-specific reharmonization"),
            sessions = listOf(
                WorkoutSession(17, "A slow arrow into the relative minor",
                    sng("Yesterday", "The Beatles", "original recording — verse only"),
                    focus = "A slow, beautiful secondary dominant pointing at a minor target. Sounds simple; it is harmonically slippery.",
                    quality = "Dominant 7 quality on a degree that is normally minor.",
                    melody = "Verse melody — the melody-harmony relationship here is unusually clear.",
                    harmonization = "Harmonize one phrase plainly, then insert the dominant arrow where the melody allows.",
                    passGoal = "You hear the arrow AND name its target, without a chart.",
                    spoiler = "Contains a secondary dominant pointing toward the relative minor, plus another dominant-function event in the bridge."),
                WorkoutSession(18, "Tonic → dominant-coloured tonic → IV",
                    sng("Something", "The Beatles", "original — full verse this time"),
                    focus = "Now take the whole verse: the tonic gains dominant colour and moves to IV, over a chromatic line.",
                    quality = "I against I7 — the same root, one note different, completely different direction.",
                    melody = "Verse melody in 2–3 note chunks.",
                    harmonization = "Level 2 opens: the melody may be the 7th when the function is clear.",
                    passGoal = "You can produce the I → I7 → IV move yourself and hear why the 7th creates the pull.",
                    spoiler = "I → I7 (V7/IV) → IV with line-cliché chromatic motion; the full song also uses borrowed chords and a modulation — stay in the verse."),
                WorkoutSession(19, "A chain of arrows, slowly",
                    sng("Dream a Little Dream of Me", "Ella Fitzgerald & Louis Armstrong"),
                    focus = "Several dominants in a row, in a slow vocal context. Hear each as “this points there”, not as isolated chromaticism.",
                    quality = "Dominant 7 chains: VI7 → ii, III7 → vi, II7 → V.",
                    melody = "First phrase, long notes first. Over each dominant, is the melody root, 3rd, 5th or ♭7?",
                    harmonization = "Insert one dominant arrow into a plain phrase, only where the melody is a structural chord tone of it.",
                    passGoal = "Every dominant in your answer is named by where it goes.",
                    spoiler = "Dominant chains over standard harmony: I–VI7–ii–V and I–III7–vi–II7–V patterns; not every arrow resolves textbook-cleanly."),
                WorkoutSession(20, "All of Me — excerpt lab, first 8 bars ONLY",
                    sng("All of Me", "Billie Holiday", "1941 version with Lester Young — first 8 bars only"),
                    songNote = "Do NOT learn the tune. Its chord rhythm is fast and that's what exhausted you last time; most early chords last two bars, so listen for the ARROWS, not every comping chord.",
                    focus = "Hear the home area, then the first outside dominant, then the next, and where each points.",
                    quality = "Your logged misses were exactly here: vi vs VI7 and ii vs II7. Compare each pair deliberately.",
                    melody = "Opening phrase only, slowly.",
                    harmonization = "Diatonic version first (I–vi–ii–V), then restore only the arrows you can actually hear.",
                    passGoal = "Identify at least two outside dominants by their targets — an improvement on your logged 4.5/10 chord-quality accuracy.",
                    spoiler = "First 8 bars simplified: I | V/vi | V/ii | ii | V/vi | vi | V/V | ii V | I — in C: C | E7 | A7 | Dm | E7 | Am | D7 | Dm G7 | C. Your earlier answer had iv where vi/VI7 belonged, and missed VI7→ii and II7→V."),
            )),

        WorkoutWeek(6, 2, "iii vs III7 · vi vs VI7 · ii vs II7 — the named bottleneck",
            prediction = "Predict quality as well as function: before each change, guess “diatonic or arrow?” Track your hit rate across a whole song.",
            notGraded = listOf("Extensions", "Exact voicings", "Inner-voice movement"),
            sessions = listOf(
                WorkoutSession(21, "Plain chord against dominant arrow",
                    sng("All of Me", "Billie Holiday", "1941 — first 8 bars, second pass"),
                    focus = "Return to the same excerpt and fix the exact misses. Compare I–iii–vi with I–III7–vi, then I–vi–ii with I–VI7–ii.",
                    quality = "iii (soft) vs III7 (directional); vi (soft) vs VI7 (pushing at ii); ii (pre-dominant) vs II7 (pushing at V).",
                    melody = "Opening phrase more fluently than last week.",
                    harmonization = "Take I–vi–ii–V and add ONE arrow: I–V/vi–vi–ii–V or I–vi–V/ii–ii–V.",
                    passGoal = "8/10 on plain-chord-vs-arrow, and every arrow named by target.",
                    spoiler = "Same key as session 20. The contrast to internalize: a major/dominant chord on degree 3 pulls into vi far harder than diatonic iii ever does."),
                WorkoutSession(22, "Rich harmony reduced to arrows",
                    sng("Georgia on My Mind", "Ray Charles", "opening only"),
                    focus = "Reduce rich harmony to simple function plus arrows. Rich chords are usually simple functions wearing colour.",
                    quality = "Ignore extensions entirely; get major/minor/dominant right first.",
                    melody = "Opening phrase, long notes first.",
                    harmonization = "Simple version first, then add one secondary dominant. Diminished approach chords are a preview only — don't force them yet.",
                    passGoal = "A usable skeleton with at most one wrong function, plus one restored arrow.",
                    spoiler = "Reduces to I, secondary dominants (V/vi, V/ii), ii, V and chromatic approach colours."),
                WorkoutSession(23, "Seventh-quality laboratory",
                    sng("Use Me", "Bill Withers", "original 1972 studio recording (Still Bill)"),
                    focus = "Two chords for a whole session. Roman-numeral function is deliberately NOT graded — this is pure quality hearing.",
                    quality = "m7 against dom7, the single most useful seventh discrimination there is. Then maj7 against m7.",
                    melody = "4–6 notes of a vocal phrase; label them against BOTH chords.",
                    harmonization = "None needed. Spend the session on quality.",
                    passGoal = "8/10 on m7-vs-dom7 and 7/10 on maj7-vs-m7, and the recorded qualities right across three consecutive alternations.",
                    spoiler = "A repeated m7 → dom7 vamp. Don't force a Roman-numeral reading."),
                WorkoutSession(24, "One chord that doesn't belong",
                    sng("Hallelujah", "Jeff Buckley", "1994 Grace recording — the first-verse passage with the first clear non-diatonic dominant, ~8 bars"),
                    focus = "Find the ONE event that sits outside the key, predict its destination, then verify.",
                    quality = "Diatonic motion to a minor chord against an applied dominant aimed at that same chord.",
                    melody = "6–8 notes across the passage; find the common tone that survives the surprise.",
                    harmonization = "Harmonize the diatonic frame, then reinstate the arrow.",
                    passGoal = "The outside chord located and its destination predicted BEFORE verification.",
                    spoiler = "In the usual C-major transcription: V7/vi → vi (E7 → Am). The diatonic frame it interrupts is I – vi – I – vi.",
                    loop = maj(1, 6, 1, 6)),
            )),

        WorkoutWeek(7, 2, "ii–V–I as one object, not three chords",
            prediction = "Bracket the music into CELLS as it plays and predict each cell's target. You're now predicting grammar, not chords.",
            notGraded = listOf("Big-band arrangement detail", "Substitutions specific to one performance", "Solo choruses"),
            sessions = listOf(
                WorkoutSession(25, "Preparation → dominant → resolution",
                    sng("Fly Me to the Moon", "Frank Sinatra with Count Basie", "or any slow vocal version"),
                    focus = "Stop hearing three chords; hear one gesture. Recognize the cell before you can name its members.",
                    quality = "m7 → m7 → dom7 → maj7. The dominant pulls harder than the minor sevenths around it.",
                    melody = "One A-section phrase; mark where the melody's arrival coincides with the cell's resolution.",
                    harmonization = "Triads first, then sevenths where the melody is root/3rd/5th/7th.",
                    passGoal = "Every cell bracketed with the right target on one guitarless pass.",
                    spoiler = "A-section direction: vi – ii – V – I circle motion (jazz charts: vi7 – ii7 – V7 – Imaj7).",
                    loop = maj(6, 2, 5, 1)),
                WorkoutSession(26, "Repeated cells and their targets",
                    sng("Satin Doll", "Duke Ellington"),
                    focus = "Repeated ii–V cells. A ii–V doesn't promise resolution — it promises a direction.",
                    quality = "ii7 against V7: the minor seventh points, the dominant pulls.",
                    melody = "One phrase over a single cell. Does the melody emphasize 3rds and 7ths?",
                    harmonization = "Harmonize a fragment with plain V–I, then expand it to ii–V–I.",
                    passGoal = "You hear ii–V as an expansion of dominant motion, not as two separate events.",
                    spoiler = "Repeated ii–V cells, each pointing at a target; the II7–V variant appears too."),
                WorkoutSession(27, "The same cell, relocated",
                    sng("Tune Up", "Miles Davis", "slow it down if needed"),
                    focus = "Every cell has identical grammar even as the target key moves. Don't panic at key changes.",
                    quality = "m7 → dom7 → maj7, repeatedly, in different keys.",
                    melody = "Opening melody slowly; mark where each phrase resolves.",
                    harmonization = "Simplify one ii–V–I to V–I, then restore it.",
                    passGoal = "You follow the structure and name most target keys correctly.",
                    spoiler = "ii–V–I cells moving through several key centres."),
                WorkoutSession(28, "Roots first, quality later",
                    sng("Autumn Leaves", "Cannonball Adderley / Miles Davis", "or a slow vocal version"),
                    focus = "Track ROOT MOTION first — descending fifths — then refine quality. Root movement is easier to hear than exact quality; start there.",
                    quality = "m7 → dom7 → maj7 in the relative major, then a minor cadence with a m7♭5 and a MAJOR V.",
                    melody = "A-section melody slowly; this melody spells the sequence out for you.",
                    harmonization = "Simplify a cadence, then restore the preparatory chord.",
                    passGoal = "Reduce the A section to large functional movement with at most one wrong function in eight events.",
                    spoiler = "ii – V – I plus circle-of-fifths motion in the relative major (in C: Dm7 – G7 – Cmaj7 – Fmaj7), then the parallel-minor ii – V – i with a major V.",
                    loop = maj(2, 5, 1, 4)),
            )),

        WorkoutWeek(8, 2, "Bass position vs chord identity — and the Month 2 exam",
            prediction = "Two-layer prediction: predict the next function AND whether the bass will be the root or another chord tone.",
            notGraded = listOf("Organ fills", "Accompaniment rhythm", "Suspension colour that doesn't change chord identity"),
            sessions = listOf(
                WorkoutSession(29, "A stepping bass is not a new chord",
                    sng("No Woman, No Cry", "Bob Marley and the Wailers", "1975 Live! version, Lyceum Theatre, London"),
                    focus = "Decide the underlying harmony FIRST, then decide whether the bass is the root or another chord tone. Never invent a root because the bass moved by step.",
                    quality = "Root position against first inversion — the dominant with its 3rd in the bass is the graded one.",
                    melody = "Six notes of a refrain phrase over the moving bass.",
                    harmonization = "Harmonize with triads, deliberately choosing the bass note for each chord.",
                    passGoal = "A chord map that doesn't change when you add the bass layer.",
                    spoiler = "Key C major: I – V6 – vi – IV | I – IV – I – V (C – G/B – Am – F | C – F – C – G).",
                    loop = maj(1, 5, 6, 4)),
                WorkoutSession(30, "Minor tonic, iv, and the minor dominant",
                    sng("Blue Bossa", "Kenny Dorham", "or the Dexter Gordon version"),
                    focus = "Establish home and its mode first — a minor tonic changes every other label. Then find the iv and the point where the key shifts.",
                    quality = "The natural v against the MAJOR V in a minor key: both are “the fifth chord” and only one pulls. Plus m7♭5.",
                    melody = "Main melody; is the 7th degree raised or lowered?",
                    harmonization = "Triads first; sevenths only where the function is obvious.",
                    passGoal = "Correct tonal centre and mode, the iv located, and the minor-vs-major dominant call right 7 times in 10.",
                    spoiler = "Minor tonic area with iv and ii°(m7♭5) – V(major, harmonic minor) – i, plus a ii–V into the relative major mid-form.",
                    loop = Progression(TrainingMode.Minor, listOf(1, 4, 2, 5), dominantBars = setOf(3))),
                WorkoutSession(31, "Blind standard drill",
                    song = null, songNote = "An unfamiliar old standard or easy jazz tune — vocal version preferred.",
                    focus = "Apply the whole month with nothing prepared: cells, arrows, inversions.",
                    quality = "maj7 / m7 / dom7 called in time.",
                    melody = "One phrase, 6–8 notes.",
                    harmonization = "Simplify the harmony first, then add one seventh or one arrow if clear.",
                    passGoal = "You produce a usable simplified lead-sheet version of a tune you've never played."),
                WorkoutSession(32, "MONTH 2 EXAMINATION",
                    song = null, songNote = "An unfamiliar standard-like song, or a simple pop song with at least one outside dominant.",
                    focus = "See the Month 2 exam card. Every dominant must be named by its target.",
                    quality = "maj7 / m7 / dom7 / plain triads, plus ii-vs-IV and iii-vs-vi where relevant.",
                    melody = "A 6–8 note phrase with correct contour.",
                    harmonization = "Level-2 harmonization that sounds musical.",
                    passGoal = "Pass if you can accompany it, explain its functions, and reshape a small section."),
            )),

        // ---------------------------------- MONTH 3 ----------------------------------
        WorkoutWeek(9, 3, "Borrowed iv — the bittersweet minor subdominant",
            prediction = "Predict colour: before a phrase repeats, guess whether it will stay diatonic or darken. Borrowed chords are extremely predictable once you expect them.",
            notGraded = listOf("Production effects", "Sped-up or overdubbed parts", "Passing tones"),
            sessions = listOf(
                WorkoutSession(33, "A chord changes clothes",
                    sng("In My Life", "The Beatles", "original 1965 recording"),
                    focus = "Hear a major chord turn minor as COLOUR, not as a wrong chord. Its root and its job stay; only the 3rd swaps.",
                    quality = "Major IV against minor iv — the same root, opposite 3rd.",
                    melody = "Main phrase; find the note that makes the borrowed colour audible.",
                    harmonization = "Two versions: diatonic, then with iv — allowed only when the melody is 4, ♭6 or 1.",
                    passGoal = "Locate the borrowed chord and still name its function correctly.",
                    spoiler = "Borrowed/minor-colour moments: IV → iv → I-type motion where the pre-dominant briefly turns minor."),
                WorkoutSession(34, "Chromatic bass under borrowed colour",
                    sng("Blackbird", "The Beatles", "original"),
                    focus = "Track the bass first: is it moving diatonically or chromatically? Then separate essential function from decorative motion.",
                    quality = "Borrowed colour against ordinary diatonic motion.",
                    melody = "Short fragments, not the whole tune.",
                    harmonization = "Make a simpler diatonic harmonization of one fragment, keeping the melody a triad tone or 7th; then compare colours.",
                    passGoal = "You can say which chords are structural and which are chromatic decoration.",
                    spoiler = "Chromatic bass motion with modal mixture; the guitar part often implies more harmony than it states."),
                WorkoutSession(35, "One melody, three harmonic colours",
                    sng("Sleep Walk", "Santo & Johnny", "original"),
                    focus = "A slow instrumental melody is the perfect bridge from note-by-note to phrase hearing — and it survives several harmonic colours.",
                    quality = "Triads, then sevenths, then one arrow, then borrowed iv. Same melody throughout.",
                    melody = "Main melody, aiming at phrase chunks. This is your best melody-training vehicle of the month.",
                    harmonization = "Three versions: triads only · sevenths allowed · one secondary dominant or minor iv.",
                    passGoal = "You feel how harmony colour changes while the melody stays stable.",
                    spoiler = "A 1950s loop (I–vi–IV–V family) with richer dominant/borrowed colours depending on the arrangement.",
                    loop = maj(1, 6, 4, 5)),
                WorkoutSession(36, "Borrowed colour in a modern song",
                    sng("Creep", "Radiohead", "original"),
                    focus = "A different context for the same device: a chord borrowed from the parallel mode, used as the emotional hinge of the song.",
                    quality = "Major against minor on the same root, in a loop simple enough that the colour is unmissable.",
                    melody = "Main vocal phrase.",
                    harmonization = "Harmonize one phrase three ways and explain why the “weird” chord works.",
                    passGoal = "You can describe the borrowed chord's colour in words before naming it.",
                    spoiler = "A four-chord loop whose third and fourth chords involve modal mixture — the borrowed chord is the hook."),
            )),

        WorkoutWeek(10, 3, "♭VII is not V",
            prediction = "Before each arrival at home, predict whether the approach will PULL (leading tone) or RELAX (lowered 7th).",
            notGraded = listOf("Orchestral builds and fades", "Backing vocals", "Guitar tone and effects"),
            sessions = listOf(
                WorkoutSession(37, "Two ways to come home",
                    sng("Hey Jude", "The Beatles", "original 1968 recording — chorus and outro vamp"),
                    focus = "Distinguish modal rock colour from classical dominant function. Both land home and mean completely different things.",
                    quality = "♭VII major against V dominant: ♭VII has no leading tone, so it relaxes into home instead of pulling.",
                    melody = "Outro melody; is the 7th degree natural or lowered?",
                    harmonization = "Two endings: IV–V–I and ♭VII–IV–I. Use ♭VII only when the melody is ♭7, 2 or 4.",
                    passGoal = "8/10 on ♭VII-vs-V, guitarless.",
                    spoiler = "Modal rock colour in the outro vamp: compare ♭VII – IV – I with IV – V – I."),
                WorkoutSession(38, "Textbook I – ♭VII – IV",
                    sng("Sweet Home Alabama", "Lynyrd Skynyrd", "original"),
                    focus = "The clearest ♭VII in the repertoire — and a genuinely ambiguous tonal centre. Decide what you hear as home and justify it.",
                    quality = "All majors; the lesson is which one is home.",
                    melody = "Main vocal phrase.",
                    harmonization = "Harmonize one phrase in each of the two candidate keys and compare.",
                    passGoal = "You can argue for a tonal centre from the music, not from the chart.",
                    spoiler = "I – ♭VII – IV, repeating. Whether you hear it centred on the first or the third chord is a real ambiguity, and useful: “key” is not always obvious."),
                WorkoutSession(39, "Modal, not dominant",
                    sng("Norwegian Wood (This Bird Has Flown)", "The Beatles", "original"),
                    focus = "Modal colour where a dominant would normally sit, plus a genuine modal shift between sections.",
                    quality = "Mixolydian ♭7 colour against a real dominant.",
                    melody = "Verse melody; the scale itself tells you which 7th is in play.",
                    harmonization = "Harmonize the phrase once modally and once with a real dominant; compare.",
                    passGoal = "No ♭VII called a V, in either section.",
                    spoiler = "Modal mixture between sections; the verse leans Mixolydian and the middle section changes mode."),
                WorkoutSession(40, "One more ♭VII, at speed",
                    sng("Werewolves of London", "Warren Zevon", "original"),
                    focus = "Same device, faster loop, so the call has to be reflexive.",
                    quality = "♭VII vs V with no time to think.",
                    melody = "Main hook.",
                    harmonization = "Build a plain diatonic alternative to the loop, then restore the borrowed colour.",
                    passGoal = "You call the loop in time on the second listen.",
                    spoiler = "A short repeating loop in the I – ♭VII – IV family."),
            )),

        WorkoutWeek(11, 3, "♭VI, ♭III, and minor-key function",
            prediction = "Predict which mode the next section will be in. Sections change mode far more often than you'd expect.",
            notGraded = listOf("Percussion layers", "Later-section bass inversions", "Instrumental doubling of chord tones"),
            sessions = listOf(
                WorkoutSession(41, "Minor tonic with borrowed drama",
                    sng("While My Guitar Gently Weeps", "The Beatles", "original"),
                    focus = "Minor-key function with borrowed colour, and a chorus that changes mode. Track the bass carefully.",
                    quality = "Minor tonic against relative-major colour; ♭VI as a dramatic arrival.",
                    melody = "Main phrase.",
                    harmonization = "Create a darker reharmonization using one borrowed chord, melody intact.",
                    passGoal = "You name the mode of each section and every borrowed chord's colour.",
                    spoiler = "A minor verse with descending motion and borrowed colour, moving to a major chorus."),
                WorkoutSession(42, "Minor loop, chromatic descent",
                    sng("Hotel California", "Eagles", "original"),
                    focus = "A long minor loop that keeps borrowing. Reduce it to a functional skeleton before naming anything.",
                    quality = "Minor i, major ♭VI and ♭VII, plus a major V in a minor key.",
                    melody = "Verse melody phrase.",
                    harmonization = "Simplify the loop to four functions, then restore the colours you can hear.",
                    passGoal = "A usable skeleton with at most one wrong function.",
                    spoiler = "An eight-chord minor loop containing ♭VI and ♭VII plus a major dominant — the major V in minor is the giveaway."),
                WorkoutSession(43, "Major/minor ambiguity",
                    sng("House of the Rising Sun", "The Animals", "original / traditional"),
                    focus = "Minor tonic with borrowed majors, and the ambiguity between minor and its relative major.",
                    quality = "Minor triads against the borrowed majors around them.",
                    melody = "Main vocal phrase.",
                    harmonization = "Harmonize the phrase in minor, then in its relative major, and describe the difference.",
                    passGoal = "You commit to a tonal centre and can defend it.",
                    spoiler = "A minor-key loop containing ♭III, ♭VI and ♭VII plus a major dominant."),
                WorkoutSession(44, "Minor i – VI – V under a dense arrangement",
                    sng("Believer", "Imagine Dragons", "original 2017 studio recording — first verse only"),
                    focus = "Establish a minor centre and track a compact framework under heavy production. Do not analyse later sections.",
                    quality = "Minor tonic vs major VI vs major V in minor.",
                    melody = "One rhythmically clear 4–6 note vocal cell.",
                    harmonization = "Harmonize the cell in minor with triads only.",
                    passGoal = "Correct tonal centre and every recurring harmony by broad quality.",
                    spoiler = "Normalized: i – VI – V (in B♭ minor: B♭m – G♭ – F).",
                    loop = Progression(TrainingMode.Minor, listOf(1, 6, 5, 5), dominantBars = setOf(2, 3))),
            )),

        WorkoutWeek(12, 3, "Girl — properly this time — and the Month 3 exam",
            prediction = "Predict across a section boundary: at the end of a verse, predict whether the next section keeps this home or moves.",
            notGraded = listOf("The famous breath sound", "Acoustic ornaments", "Anything outside the assigned fragment"),
            sessions = listOf(
                WorkoutSession(45, "Girl, verse — iv-area to relative major",
                    sng("Girl", "The Beatles", "original 1965 — verse second half only"),
                    songNote = "You now have the vocabulary this needs. Your earlier miss was reasonable: the chord you couldn't place is almost the same pitch collection as the minor iv with a different bass, so it behaves like iv-family colour rather than a dramatic new function.",
                    focus = "Hear iv-area colour moving to the relative major, then the dominant back to minor. Don't force the second chord to be a huge new function.",
                    quality = "Minor iv, its 6th/7th-flavoured neighbour, a warm major resting chord, then dominant 7.",
                    melody = "One phrase you already know, played fluently.",
                    harmonization = "Harmonize the fragment with i, iv and the relative major only.",
                    passGoal = "You can describe the move as “subdominant colour → relative-major rest → dominant back home”.",
                    spoiler = "iv → ♭VI6 (≈ iv7 with ♭6 in the bass) → ♭III → V7, in C minor: Fm → A♭6 → E♭ → G7. A♭6 and Fm7 are the same collection heard from different roots — which is exactly why it didn't announce itself as ♭VI."),
                WorkoutSession(46, "Girl, chorus — iii is not vi, ii is not IV",
                    sng("Girl", "The Beatles", "original 1965 — chorus only"),
                    focus = "The chorus really does move home to the relative major — your instinct was right. What was wrong was the inner colour.",
                    quality = "iii (weak, smooth tonic-family) against vi (emotional relative minor); ii (directed pre-dominant) against IV (broad subdominant).",
                    melody = "Chorus phrase, fluent.",
                    harmonization = "Play the chorus loop, then the doo-wop loop, back to back, until the two middle chords stop sounding interchangeable.",
                    passGoal = "8/10 on iii-vs-vi and ii-vs-IV, and you can explain why your original guess was right in shape and wrong in quality.",
                    spoiler = "Chorus in the relative major: I – iii – ii – V7 (E♭ – Gm – Fm – B♭7). Doo-wop for comparison: I – vi – IV – V (E♭ – Cm – A♭ – B♭). Same broad shape — tonic → softer chord → pre-dominant → dominant — different inner functions.",
                    loop = maj(1, 3, 2, 5)),
                WorkoutSession(47, "Chromatic bass under a static function",
                    sng("Something Stupid", "Frank & Nancy Sinatra", "original"),
                    songNote = "Alternative: God Only Knows — The Beach Boys, if you want a harder bass-motion study.",
                    focus = "A descending chromatic bass under harmony that barely moves. Chromatic motion is decoration over function far more often than it is new function.",
                    quality = "Real functional change against chromatic decoration.",
                    melody = "Main phrase; find the notes that stay put while the bass moves.",
                    harmonization = "Harmonize the phrase with static function and a moving bass, then with real changes; compare.",
                    passGoal = "Every genuine functional change caught, and no decoration promoted to a function.",
                    spoiler = "A chromatically descending line under a prolonged tonic area, with a secondary dominant at the cadence."),
                WorkoutSession(48, "MONTH 3 EXAMINATION",
                    song = null, songNote = "An unfamiliar song containing modal mixture — Beatles or classic rock is ideal.",
                    focus = "See the Month 3 exam card. Classify every non-diatonic chord as borrowed, modal or applied dominant.",
                    quality = "Borrowed colour vs modal motion vs dominant function.",
                    melody = "An 8–10 note phrase.",
                    harmonization = "Use one borrowed chord in your own harmonization, melody intact.",
                    passGoal = "Pass with a usable skeleton, at most one wrong function, and no modal chord called a dominant."),
            )),

        // ---------------------------------- MONTH 4 ----------------------------------
        WorkoutWeek(13, 4, "Diminished chords as motion, not as strange chords",
            prediction = "When you hear a diminished sound, predict its resolution BEFORE it arrives: #I° wants ii, #ii° wants iii, #iv° wants V.",
            notGraded = listOf("Cavaquinho/pandeiro accompaniment detail", "Extensions and added 6ths/9ths", "Rubato in intros"),
            sessions = listOf(
                WorkoutSession(49, "Samba diminished — where does it resolve?",
                    sng("Trem das Onze", "Adoniran Barbosa", "original"),
                    songNote = "You've already been studying this one — now do it as a diminished lab.",
                    focus = "Track the bass first, then locate each diminished chord by WHERE IT RESOLVES rather than by its name.",
                    quality = "Diminished passing chord against a real functional change.",
                    melody = "Main vocal phrase.",
                    harmonization = "Create a simpler version WITHOUT the diminished chords, then reinstate one.",
                    passGoal = "Every diminished chord named by its target, and a simplified version that still sounds like the song.",
                    spoiler = "Diminished chords act as chromatic approach: #I° → ii, #ii° → iii, #iv° → V, over otherwise functional samba harmony."),
                WorkoutSession(50, "Samba harmony, second pass",
                    sng("Na Minha Casa", "Martinho da Vila", "original"),
                    focus = "Same grammar, different tune: functional samba harmony with chromatic connective tissue.",
                    quality = "Dominant sevenths against diminished approach chords — both “tense”, completely different motion.",
                    melody = "Main phrase; note the long tones over changing harmony.",
                    harmonization = "Harmonize one phrase in a simpler samba style, keeping the function.",
                    passGoal = "You can accompany a verse and explain each chromatic chord's job.",
                    spoiler = "Functional samba harmony with secondary dominants and diminished passing chords between diatonic arrivals."),
                WorkoutSession(51, "The diminished approach in a standard",
                    sng("Georgia on My Mind", "Ray Charles", "opening — third pass, now for the diminished move"),
                    focus = "You reduced this to arrows in month 2. Now hear the chromatic approach chord you were told to skip back then.",
                    quality = "#I° → ii against V/ii → ii: two different ways to approach the same target.",
                    melody = "Opening phrase, more fluent than in month 2.",
                    harmonization = "Approach ii once by its dominant and once by a diminished chord; compare.",
                    passGoal = "You can choose between a dominant approach and a diminished approach deliberately.",
                    spoiler = "The opening contains both a I → #I° → ii chromatic approach and secondary dominants aimed at vi and ii."),
                WorkoutSession(52, "Bossa with dominants and chromatic bass",
                    sng("Wave", "Antônio Carlos Jobim", "original"),
                    focus = "Rich functional bossa harmony: track the secondary dominants and predict their targets.",
                    quality = "maj7 / m7 / dom7 / diminished, all as ordinary colour rather than events.",
                    melody = "Main melody; long notes over changing chords.",
                    harmonization = "Build a simple guitar comping version that keeps the function intact.",
                    passGoal = "A usable chart with each dominant's target named.",
                    spoiler = "Dominant-rich bossa harmony over a chromatically descending plan, with diminished and chromatic approach chords."),
            )),

        WorkoutWeek(14, 4, "Chromatic dominants in bossa — II7, VI7, III7",
            prediction = "Predict the target of every chromatic dominant. Then predict whether the tune will actually go there or move on.",
            notGraded = listOf("Saxophone/instrumental embellishments", "Vocal phrasing against the beat", "6th/9th colour on the tonic"),
            sessions = listOf(
                WorkoutSession(53, "The one bright chord in a calm A section",
                    sng("Garota de Ipanema (The Girl from Ipanema)", "João & Astrud Gilberto with Stan Getz", "Getz/Gilberto, 1964"),
                    focus = "A chromatic dominant on the second degree brightens the A section without breaking it. Then the bridge leaves the key entirely — map it as root motion first.",
                    quality = "Diatonic ii7 against chromatic II7. This is the single most useful bossa discrimination.",
                    melody = "A-section melody, then the first bridge phrase — label each against its OWN tonic.",
                    harmonization = "Harmonize the A section diatonically, then insert the chromatic dominant where the melody permits.",
                    passGoal = "The II7 located with the right target, and the bridge's broad path traced.",
                    spoiler = "In F: Fmaj7 – G7 – Gm7 – G♭7 – Fmaj7. The G7 is II7 (V/V) resolving toward the dominant area; the bridge moves to a new centre and returns by ii–V."),
                WorkoutSession(54, "Chains of ii–V that don't all resolve",
                    sng("Corcovado (Quiet Nights of Quiet Stars)", "João Gilberto with Stan Getz", "Getz/Gilberto, 1964"),
                    focus = "Follow a chain of cells over a slowly descending plan, where some dominants are substituted for the ones you predicted.",
                    quality = "The expected dominant against a substitute a tritone away — they share their most important notes.",
                    melody = "A full A-section melody: contour first, then exact pitches.",
                    harmonization = "Harmonize the structural notes with sevenths where the function is clear (Level 3 opens here).",
                    passGoal = "Map the form with ≥75% of events right, each dominant identified by where it actually goes.",
                    spoiler = "A chain of ii–V cells with chromatic/substitute dominants standing in for expected ones. Reduce to “cell → target” first, then refine the substitutions."),
                WorkoutSession(55, "Bossa at speed",
                    sng("Só Danço Samba", "Antônio Carlos Jobim", "original"),
                    focus = "The same grammar with a brighter tempo, so the calls must be reflexive.",
                    quality = "II7 vs ii7 and dom7 vs maj7, called in time.",
                    melody = "Main melody in phrase chunks.",
                    harmonization = "Comp the A section from your own functional reading, no chart.",
                    passGoal = "You accompany it in real time after one listen through.",
                    spoiler = "A ii–V-driven A section with chromatic dominants; the bridge shifts key briefly."),
                WorkoutSession(56, "Deliberately “out of tune” harmony",
                    sng("Desafinado", "João Gilberto", "original"),
                    focus = "A tune whose subject is harmonic sophistication: chromatic dominants, diminished motion and a modulating bridge.",
                    quality = "All four qualities plus diminished, inside one form.",
                    melody = "A-section melody; mark the notes that create the “off-key” feeling.",
                    harmonization = "Reduce a phrase to plain function, then restore one chromatic device.",
                    passGoal = "You can reduce dense bossa harmony to function without losing the song.",
                    spoiler = "Chromatic dominants and diminished approach chords over a bossa A section, with a modulating bridge."),
            )),

        WorkoutWeek(15, 4, "Modulation and chromatic descent",
            prediction = "Predict the modulation: at a section boundary, predict whether home will move and to where (relative major/minor is the usual answer).",
            notGraded = listOf("Guitar voicing and beat placement", "Extensions", "Exact bass rhythm"),
            sessions = listOf(
                WorkoutSession(57, "Two homes in one song",
                    sng("Chega de Saudade", "João Gilberto", "1958/59 original recording"),
                    focus = "Hear a MODULATION: the minor first half moving to the major second half. A modulation feels like the floor moving, not like a wrong chord.",
                    quality = "Minor tonic against major tonic — as tonics, not as chords.",
                    melody = "The opening gesture (it's also the descending minor-6th reference in this app's Theory tab) plus the first phrase of the major section.",
                    harmonization = "Harmonize both phrases, each against its own tonic.",
                    passGoal = "Both tonics correct and the pivot located within a bar or two.",
                    spoiler = "A minor-key opening section modulating to the major for the second half, with chromatic descending motion and diminished approach chords inside the minor section."),
                WorkoutSession(58, "A whole tune built on the descent",
                    sng("Insensatez (How Insensitive)", "Antônio Carlos Jobim", "original"),
                    focus = "A literal chromatic descending sequence. Identify it as a SEQUENCE, then name the function each chromatic chord decorates.",
                    quality = "Chromatic decoration against genuine functional change.",
                    melody = "A-section melody; the melody descends with the harmony.",
                    harmonization = "Harmonize the sequence with fewer chords, keeping the descent audible.",
                    passGoal = "The sequence heard as one gesture, with its underlying functions named.",
                    spoiler = "A descending sequence of root motion with dominants and diminished chords connecting the steps, resolving through a minor cadence."),
                WorkoutSession(59, "Smooth chromatic harmony",
                    sng("Meditação", "Antônio Carlos Jobim", "original"),
                    songNote = "Alternative: Triste, or Dindi, if you want a different melodic challenge.",
                    focus = "Chromatic harmony that never feels chromatic. Track bass motion and predict the cadences.",
                    quality = "maj7 / m7 / dom7 in close succession, as ordinary colour.",
                    melody = "A 10-second vocal phrase, exact.",
                    harmonization = "Create a less chromatic reharmonization that still supports the melody.",
                    passGoal = "You predict most cadences before they land.",
                    spoiler = "Smooth chromatic voice-leading over functional cadences; the bass line is the clearest guide."),
                WorkoutSession(60, "One-note melody, all harmony",
                    sng("Samba de Uma Nota Só (One Note Samba)", "Antônio Carlos Jobim", "original"),
                    songNote = "Alternative: O Barquinho — Roberto Menescal.",
                    focus = "The melody barely moves, so the harmony is completely exposed. This is the purest functional-hearing test in the repertoire.",
                    quality = "Every chord change under a static melody note — quality is all there is.",
                    melody = "The A-section melody (trivially easy — that's the point). Label the static note against each chord.",
                    harmonization = "Reharmonize the static melody note three different ways and explain each.",
                    passGoal = "Every chord under the repeated note identified by quality and function.",
                    spoiler = "A descending chromatic bass under an almost static melody; each chord recolours the same melody note (root → 7th → 5th → ♭9 …)."),
            )),

        WorkoutWeek(16, 4, "Consolidation and the final examination",
            prediction = "Full real-time test: play along with an unfamiliar song from the second verse onward, then write the progression afterwards from memory.",
            notGraded = listOf("Anything you can't verify by ear", "Voicings — function is what's graded"),
            sessions = listOf(
                WorkoutSession(61, "Redo one Brazilian tune from memory",
                    song = null, songNote = "Pick any tune from weeks 13–15 and redo it without notes.",
                    focus = "Compare your first attempt with your corrected version. Simplify each progression, then restore its richness.",
                    quality = "All qualities, from memory.",
                    melody = "Play the melody without hunting.",
                    harmonization = "Simplify to a “campfire” version, then restore the original colours.",
                    passGoal = "You reproduce your own analysis without notes, and the simplification still sounds like the song."),
                WorkoutSession(62, "Blind bossa/samba",
                    song = null, songNote = "An unfamiliar samba or bossa nova.",
                    focus = "Everything from month 4, cold: form, cadences, chromatic and diminished devices.",
                    quality = "maj7 / m7 / dom7 / diminished in a full arrangement.",
                    melody = "The main melody.",
                    harmonization = "A usable chart plus a simpler performance version.",
                    passGoal = "A usable chord chart and at least one chromatic/diminished device named by its resolution."),
                WorkoutSession(63, "Blind Beatles / classic rock",
                    song = null, songNote = "An unfamiliar Beatles or classic-rock song you don't know well.",
                    focus = "Don't finish the song. Find ONE difficult 4-bar section and get it completely right: borrowed colour, iii vs vi, ii vs IV, ♭VII vs V.",
                    quality = "The full month-3 vocabulary, in a section chosen because it's hard.",
                    melody = "One difficult phrase only.",
                    harmonization = "Harmonize two bars under the constraints.",
                    passGoal = "You diagnose one 4-bar section instead of exhausting yourself on the whole song — the lesson your first Girl attempt taught."),
                WorkoutSession(64, "FINAL EXAMINATION",
                    song = null, songNote = "An unfamiliar song of your choice — prefer one with a modulation or at least one chromatic dominant.",
                    focus = "See the Month 4 exam card. One listen, then 90 minutes.",
                    quality = "Every quality, named in time.",
                    melody = "The main melody, played not hunted.",
                    harmonization = "One alternative harmonization, plus a performance from your own lead sheet.",
                    passGoal = "You can hear, understand, play and RESHAPE real music. That's the whole plan."),
            )),
    )

    /** What Claude changed, and why (shown in-app). */
    val REVISION_NOTES: List<String> = listOf(
        "MERGED into one plan. Your two curriculum PDFs were competing drafts, and the earlier build showed them as parallel “Track A / Track B”. There is now a single curriculum: the strict plan's structure (one bounded assignment per session, explicit not-graded lists, exam gates) carrying the broad plan's repertoire and spiral design.",
        "EXPANDED 8 weeks → 16 weeks (4 months, 64 sessions), and re-derived the arc from your own conversation rather than from the two summary PDFs alone — which changed the plan substantially.",
        "ORGANIZED BY HARMONIC CONCEPT, one new listening objective per month, which is the idea you and ChatGPT converged on: month 1 diatonic function+quality at speed → month 2 dominant arrows / sevenths / ii–V → month 3 borrowed colour and modal mixture → month 4 Brazilian harmony: diminished motion, chromatic dominants, modulation.",
        "ADDED THE MISSING CONCEPT: diminished passing chords (#I°→ii, #ii°→iii, #iv°→V) got a full week. They were on your concept ladder as level 5 and you already analyse them in Brazilian music, but the earlier build skipped them entirely.",
        "SPIRAL, NOT BLOCKS: harmony, melody, bass, harmonization AND a prediction drill appear every single week from week 1 — only the complexity rises. Harmonization does not wait for month 5; melody has a per-month stage (note-by-note → 2–3 note chunks → short phrases → full A-section) matching where you actually are.",
        "SYNTHETIC PROGRESSIONS REMOVED FROM SESSIONS. They're train-ride work, in a categorized pool, exactly as you asked. Every session is a real song, and each month names which drill categories to run on the train.",
        "AIMED AT YOUR LOGGED MISSES. All of Me appears only as a bounded excerpt lab (Billie Holiday 1941, first 8 bars) and returns a week later specifically to fix vi-vs-VI7 and ii-vs-II7. Girl appears as a two-loop diagnostic in month 1 and comes back properly in month 3, where its ♭VI/♭III vocabulary lives — and its chorus is set against the doo-wop loop you mistook it for.",
        "REPERTOIRE CORRECTIONS KEPT: Three Little Birds is gone (you didn't like it) and I Can See Clearly Now takes its place; You Are My Sunshine carries the caveat that only versions with I7 → IV teach anything; the secondary-dominant ladder runs You Are My Sunshine → Something → Yesterday → Dream a Little Dream → All of Me; every standard names a performer.",
        "YOUR OWN REPERTOIRE IS THE PAY-OFF: month 4 is the bossa/samba material you actually play — Trem das Onze, Na Minha Casa, Ipanema, Corcovado, Chega de Saudade, Wave, Insensatez, One Note Samba.",
        "NO RHYTHMIC DICTATION, NO SIGHT-SINGING, NO KEY-FINDING DRILL, NO WRITTEN LOG. Rhythm is a strength, not a bottleneck; you think in scale degrees already; the guitar gives you the key in seconds; and the session's output is that you can play and explain the passage.",
        "ADDED THE MASTERY RULE, a monthly complete-transcription project, the time-scaling table, honest expected-progress percentages, and the Berklee comparison — all from your conversation, so the plan states its own success criteria instead of just listing tasks.",
        "Spoilers are appendix-only and never reveal a song's mode in the session text. Sessions whose answer is a clean 4-bar diatonic loop get a ▶ play button (key C / Am).",
    )
}
