#!/usr/bin/env python3
"""Generate the Songs-tab library for BOTH platforms from the two data files.

    docs/songs/bookmarks.json     the song list (title/artist/url/site)
    docs/songs/progressions.json  hand-maintained chord data, keyed "Artist|Title"
        ->  theory/src/main/kotlin/app/guitar/theory/SongLibrary.kt
        ->  chorect-web/src/theory/songLibrary.ts

Run after editing either input:

    python tools/build_song_library.py

Both outputs are GENERATED - never hand-edit them; edit the JSON and re-run. One
generator writing both ports is what keeps the two platforms provably identical
(chorect-web/test/verify.ts pins the TS counts/digest against the Kotlin ones).

The library is compiled INTO the app: the Songs tab does no network I/O at all.
The bookmarks are read once here, on the developer's machine, at build time.

NO LYRICS are stored here or generated. The app carries a per-song lyrics field
that the device owner fills in themselves; it lives in local storage, not in the
repo and not in the APK.
"""

import io
import json
import os
import hashlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOOKMARKS = os.path.join(ROOT, "docs", "songs", "bookmarks.json")
PROGRESSIONS = os.path.join(ROOT, "docs", "songs", "progressions.json")
KT_OUT = os.path.join(ROOT, "theory", "src", "main", "kotlin", "app", "guitar", "theory", "SongLibrary.kt")
TS_OUT = os.path.join(ROOT, "chorect-web", "src", "theory", "songLibrary.ts")


def kt_str(s):
    """Kotlin string literal. '$' starts a template, so it must be escaped too."""
    if s is None:
        return "null"
    e = s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
    return f'"{e}"'


def ts_str(s):
    if s is None:
        return "null"
    e = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{e}"'


def load():
    songs = json.load(io.open(BOOKMARKS, encoding="utf-8"))
    progs = json.load(io.open(PROGRESSIONS, encoding="utf-8"))
    progs = {k.lower(): v for k, v in progs.items() if not k.startswith("_")}

    merged, matched = [], 0
    for s in songs:
        key = f"{s['artist']}|{s['title']}".lower()
        p = progs.get(key)
        if p:
            matched += 1
        merged.append({
            "title": s["title"],
            "artist": s["artist"],
            "key": (p or {}).get("key"),
            "minor": ((p or {}).get("mode") == "minor"),
            "capo": (p or {}).get("capo", 0),
            "seeded": ((p or {}).get("source") == "seed"),
            "sections": (p or {}).get("sections", []),
            "url": s["url"],
            "site": s["site"],
        })

    unmatched = [k for k in progs if k not in {f"{s['artist']}|{s['title']}".lower() for s in songs}]
    if unmatched:
        raise SystemExit("progressions.json keys match no bookmark:\n  " + "\n  ".join(unmatched))
    return merged, matched


def digest(merged):
    """Stable fingerprint of the whole library - both ports assert the same value,
    so a one-sided edit to a generated file cannot pass CI."""
    h = hashlib.sha256()
    for s in merged:
        h.update(("|".join([
            s["title"], s["artist"], s["key"] or "", str(s["minor"]), str(s["capo"]),
            ";".join(sec["label"] + ":" + ",".join(sec["chords"]) for sec in s["sections"]),
            s["url"],
        ])).encode("utf-8"))
    return h.hexdigest()[:16]


HEADER = """// GENERATED by tools/build_song_library.py - DO NOT EDIT.
// Source: docs/songs/bookmarks.json + docs/songs/progressions.json
//
// Nadav's bookmarked song list with the chord data we have for each. Compiled INTO
// the app: the Songs tab never touches the network. Chord symbols are what SOUNDS,
// so the engine derives Roman numerals, transposes, and drives the looper from them.
// No lyrics live here - the app keeps a per-song lyrics field in local storage.
"""


def emit_kotlin(merged, matched, dg):
    L = [HEADER, "\npackage app.guitar.theory\n", "\nobject SongLibrary {"]
    L.append(f'    /** Fingerprint of the generated data; the TS port asserts the same value. */')
    L.append(f'    const val DIGEST = "{dg}"\n')
    L.append("    data class Section(val label: String, val chords: List<String>)\n")
    L.append("""    data class Song(
        val title: String,
        val artist: String,
        /** Tonic as a chord symbol ("G", "Am"); null while the song has no chord data. */
        val key: String?,
        val minor: Boolean,
        /** Fret the common arrangement capos at; 0 = none. Informational - [sections]
         *  always holds SOUNDING chords, so playback and analysis ignore it. */
        val capo: Int,
        /** True when the chords were seeded from common musical knowledge rather than
         *  entered by the owner - the UI marks these as correctable. */
        val seeded: Boolean,
        val sections: List<Section>,
        /** Where the owner bookmarked it; opened in a browser, never fetched by the app. */
        val url: String,
        val site: String,
    ) {
        val hasChords: Boolean get() = sections.isNotEmpty()

        /** Every distinct chord symbol in the song, in first-seen order. */
        val chordVocabulary: List<String>
            get() = sections.flatMap { it.chords }.distinct()
    }

    /** Alphabetical by artist, then title. */
    val SONGS: List<Song> = listOf(""")
    for s in merged:
        secs = ", ".join(
            "Section(%s, listOf(%s))" % (kt_str(sec["label"]), ", ".join(kt_str(c) for c in sec["chords"]))
            for sec in s["sections"]
        )
        L.append("        Song(%s, %s, %s, %s, %d, %s, listOf(%s), %s, %s)," % (
            kt_str(s["title"]), kt_str(s["artist"]), kt_str(s["key"]),
            "true" if s["minor"] else "false", s["capo"],
            "true" if s["seeded"] else "false", secs,
            kt_str(s["url"]), kt_str(s["site"]),
        ))
    L.append("    )\n")
    L.append("""    /** Songs that already carry chord data. */
    val WITH_CHORDS: List<Song> get() = SONGS.filter { it.hasChords }

    /** Distinct artists, alphabetical; the blank artist (unparsed bookmarks) is dropped. */
    val ARTISTS: List<String> get() = SONGS.map { it.artist }.filter { it.isNotBlank() }.distinct()

    /** Case-insensitive substring match over title and artist. Blank query = everything. */
    fun search(query: String): List<Song> {
        val q = query.trim().lowercase()
        if (q.isEmpty()) return SONGS
        return SONGS.filter { it.title.lowercase().contains(q) || it.artist.lowercase().contains(q) }
    }
}
""")
    io.open(KT_OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))


def emit_ts(merged, matched, dg):
    L = [HEADER, "\n/** Fingerprint of the generated data; must equal Kotlin SongLibrary.DIGEST. */",
         f'export const SONG_LIBRARY_DIGEST = "{dg}";\n',
         "export interface SongSection {\n  label: string;\n  chords: string[];\n}\n",
         """export interface Song {
  title: string;
  artist: string;
  /** Tonic as a chord symbol ("G", "Am"); null while the song has no chord data. */
  key: string | null;
  minor: boolean;
  /** Fret the common arrangement capos at; 0 = none. Informational - `sections`
   *  always holds SOUNDING chords, so playback and analysis ignore it. */
  capo: number;
  /** True when the chords were seeded from common musical knowledge rather than
   *  entered by the owner - the UI marks these as correctable. */
  seeded: boolean;
  sections: SongSection[];
  /** Where the owner bookmarked it; opened in a new tab, never fetched by the app. */
  url: string;
  site: string;
}

/** Alphabetical by artist, then title. */
export const SONGS: Song[] = ["""]
    for s in merged:
        secs = ", ".join(
            "{ label: %s, chords: [%s] }" % (ts_str(sec["label"]), ", ".join(ts_str(c) for c in sec["chords"]))
            for sec in s["sections"]
        )
        L.append("  { title: %s, artist: %s, key: %s, minor: %s, capo: %d, seeded: %s, sections: [%s], url: %s, site: %s }," % (
            ts_str(s["title"]), ts_str(s["artist"]), ts_str(s["key"]),
            "true" if s["minor"] else "false", s["capo"],
            "true" if s["seeded"] else "false", secs,
            ts_str(s["url"]), ts_str(s["site"]),
        ))
    L.append("""];

export function songHasChords(s: Song): boolean { return s.sections.length > 0; }

/** Every distinct chord symbol in the song, in first-seen order. */
export function songChordVocabulary(s: Song): string[] {
  const seen: string[] = [];
  for (const sec of s.sections) for (const c of sec.chords) if (!seen.includes(c)) seen.push(c);
  return seen;
}

/** Songs that already carry chord data. */
export const SONGS_WITH_CHORDS: Song[] = SONGS.filter(songHasChords);

/** Distinct artists, alphabetical; the blank artist (unparsed bookmarks) is dropped. */
export const SONG_ARTISTS: string[] = SONGS.map((s) => s.artist).filter((a) => a.trim().length > 0)
  .filter((a, i, all) => all.indexOf(a) === i);

/** Case-insensitive substring match over title and artist. Blank query = everything. */
export function searchSongs(query: string): Song[] {
  const q = query.trim().toLowerCase();
  if (!q) return SONGS;
  return SONGS.filter((s) => s.title.toLowerCase().includes(q) || s.artist.toLowerCase().includes(q));
}
""")
    io.open(TS_OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))


def main():
    merged, matched = load()
    dg = digest(merged)
    emit_kotlin(merged, matched, dg)
    emit_ts(merged, matched, dg)
    print(f"{len(merged)} songs ({matched} with chord data), digest {dg}")
    print(f"  -> {os.path.relpath(KT_OUT, ROOT)}")
    print(f"  -> {os.path.relpath(TS_OUT, ROOT)}")


if __name__ == "__main__":
    main()
