#!/usr/bin/env python3
"""Regenerate the Android launcher icon from the Chorect logo.

Source of truth: docs/branding/chorect-logo.png (the lyre wordmark on its white
card). Everything under app/src/main/res/mipmap-*/ is GENERATED — edit the logo
and re-run this, never hand-edit the PNGs:

    python tools/build_launcher_icon.py

What it emits, per density bucket:
  ic_launcher.png            legacy square icon (pre-API-26 launchers)
  ic_launcher_round.png      legacy round icon (circular mask, transparent corners)
  ic_launcher_foreground.png adaptive-icon foreground layer (API 26+)

The adaptive BACKGROUND stays a one-colour vector (drawable/ic_launcher_background.xml)
matching the logo card, so the two layers meet seamlessly.

Adaptive geometry: the layer canvas is 108dp, only the central 72dp is shown, and
the largest shape every launcher mask is guaranteed to keep is a 66dp CIRCLE. The
artwork is therefore fitted by its diagonal to that circle (see SAFE_CIRCLE), not
by its bounding box to a square — square-fitting is what clipped the "t" off the
wordmark in the first build.
"""

import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "docs", "branding", "chorect-logo.png")
RES = os.path.join(ROOT, "app", "src", "main", "res")

# px per bucket: legacy launcher icon (48dp) and adaptive layer (108dp).
BUCKETS = {
    "mdpi": (48, 108),
    "hdpi": (72, 162),
    "xhdpi": (96, 216),
    "xxhdpi": (144, 324),
    "xxxhdpi": (192, 432),
}

# The adaptive layer is 108dp but only the inner 72dp is ever shown, and the
# largest shape guaranteed to survive EVERY launcher mask is a circle of 66dp
# across. So the artwork is fitted by its DIAGONAL to that circle, not by its
# bounding box to a 72dp square: a square fit puts the corners of the box outside
# the circle, which is exactly how the first build lost the "t" of "Chorect".
SAFE_CIRCLE = 66.0 / 108.0
# Saturation threshold that separates the coloured artwork from the white card.
SAT = 30


def art_bbox(im):
    """Bounding box of the COLOURED artwork — the card and page are both near-white
    (~#FDFDFD), so a plain getbbox() would return the whole image."""
    px = im.load()
    w, h = im.size
    minx, miny, maxx, maxy = w, h, 0, 0
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            if max(r, g, b) - min(r, g, b) > SAT:
                minx = min(minx, x); maxx = max(maxx, x)
                miny = min(miny, y); maxy = max(maxy, y)
    return minx, miny, maxx, maxy


def main():
    src = Image.open(SRC).convert("RGB")
    x0, y0, x1, y1 = art_bbox(src)
    # A little air around the wordmark so it doesn't touch the safe-zone edge.
    pad = int(0.04 * max(x1 - x0, y1 - y0))
    x0 = max(0, x0 - pad); y0 = max(0, y0 - pad)
    x1 = min(src.width - 1, x1 + pad); y1 = min(src.height - 1, y1 + pad)
    art = src.crop((x0, y0, x1 + 1, y1 + 1))
    card = src.getpixel((5, 5))          # the card/page white, reused by the bg vector
    print(f"artwork {art.size} cropped from {src.size}; card colour {card}")

    for bucket, (legacy, layer) in BUCKETS.items():
        out = os.path.join(RES, f"mipmap-{bucket}")
        os.makedirs(out, exist_ok=True)

        # --- legacy square: the whole logo card, as drawn ---
        sq = src.resize((legacy, legacy), Image.LANCZOS)
        sq.save(os.path.join(out, "ic_launcher.png"))

        # --- legacy round: same, circle-masked, transparent outside ---
        rnd = sq.convert("RGBA")
        mask = Image.new("L", (legacy * 4, legacy * 4), 0)
        from PIL import ImageDraw
        ImageDraw.Draw(mask).ellipse((0, 0, legacy * 4 - 1, legacy * 4 - 1), fill=255)
        rnd.putalpha(mask.resize((legacy, legacy), Image.LANCZOS))
        rnd.save(os.path.join(out, "ic_launcher_round.png"))

        # --- adaptive foreground: artwork inside the safe zone, transparent around ---
        fg = Image.new("RGBA", (layer, layer), (0, 0, 0, 0))
        diag = (art.width ** 2 + art.height ** 2) ** 0.5
        scale = (layer * SAFE_CIRCLE) / diag
        aw, ah = max(1, round(art.width * scale)), max(1, round(art.height * scale))
        fg.paste(art.resize((aw, ah), Image.LANCZOS), ((layer - aw) // 2, (layer - ah) // 2))
        fg.save(os.path.join(out, "ic_launcher_foreground.png"))
        print(f"  mipmap-{bucket}: {legacy}px legacy, {layer}px layer (art {aw}x{ah})")

    # Keep the adaptive background exactly the logo's card colour.
    hexcol = "#%02X%02X%02X" % card
    bg = os.path.join(RES, "drawable", "ic_launcher_background.xml")
    with open(bg, "w", encoding="utf-8", newline="\n") as f:
        f.write(
            '<?xml version="1.0" encoding="utf-8"?>\n'
            "<!-- GENERATED by tools/build_launcher_icon.py - the Chorect logo's card\n"
            "     colour, so the adaptive foreground meets it with no visible seam. -->\n"
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="108dp"\n'
            '    android:height="108dp"\n'
            '    android:viewportWidth="108"\n'
            '    android:viewportHeight="108">\n'
            "    <path\n"
            f'        android:fillColor="{hexcol}"\n'
            '        android:pathData="M0,0 h108 v108 h-108 z" />\n'
            "</vector>\n"
        )
    print(f"background vector -> {hexcol}")


if __name__ == "__main__":
    main()
